---

- name: Create Fabio config
  become: yes
  template:
    dest: "{{ fabio.directories.config }}/fabio.properties"
    src: fabio.properties.j2
  notify:
    - restart fabio

- name: Start Fabio service
  become: yes
  service:
    state: started
    name: fabio
