---

- name: Download the Go tarball
  become: yes
  get_url:
    url: "https://storage.googleapis.com/golang/go1.5.1.linux-amd64.tar.gz"
    dest: "/usr/local/src/go1.5.1.linux-amd64.tar.gz"
    sha256sum: "2593132ca490b9ee17509d65ee2cd078441ff544899f6afb97a03d08c25524e7"
    force: no

- name: Extract the Go tarball
  become: yes
  command: "tar -C /usr/local -xf /usr/local/src/go1.5.1.linux-amd64.tar.gz"
  args:
    creates: /usr/local/go
